### PR TITLE
A pull request to keep track of my contribution to Arcadia.

### PR DESCRIPTION
**Pull request by japandotorg**
This PR is still under-development, and is being posted for future reference and tracking purposes.

### CODE REVIEW

**Comment by cheesycod** [comment]
might be better to split macros into a seperate crate?

**Comment by japandotorg** [comment]
> might be better to split macros into a seperate crate?

yeah that'll actually be better, alright will revert changes and make a separate crate for macros

**Comment by cheesycod** [comment]
Any update?

**Comment by cheesycod** [comment]
Uhhh...

**Comment by cheesycod** [comment]
we have ``bot/leone`` for macros just fyi but core otherwise looks good

**Comment by cheesycod** [comment]
Any updates here?

**Pull request closed without merging**
